### ISSUE TITLE
authenticate using private key and certificates

### ISSUE THREAD

**Issue by erentatar** [tomcatmanager/tomcatmanager#110]
Is there any way to connect to tomcat manager over a connector configured using https ? Besides, it will need to pass some certificate file information like root cert path to establish a mutual authentication while connecting, but it seems there is no such parameters in connect method.

**Comment by kotfu** [comment]
HTTPS aka SSL aka TLS can be used to provide two major functions. By far the most common is to encrypt data between two endpoints. tomcat manager already supports this. Use "https" as the protocol in your url, like "https://www.example.com/manager" and it will work fine. tomcat manager uses the [requests](https://docs.python-requests.org/en/master/) library for all network communication.

The second major function is to authenticate users of a service using cryptographic certificates. This function requires a certificate authority to sign private keys and certificates to be used on the client side. Based on your question I think this is what you are asking about. Tomcat Manager does not currently support this capability. However, requests does, and it should be relatively simple to add the optional parameters to the `connect()` method to allow you to pass the certificate information, and then have tomcatmanager pass it through to requests. I'll mark this as an enhancement and investigate.

**Comment by erentatar** [comment]
Yes, the second one is what I want to accomplish. I have already been accessing my web apps over https. It is configured as 

`<Connector port="8447" scheme="https" secure="true" SSLEnabled="true" maxThreads="150" sslImplementationName="org.apache.tomcat.util.net.openssl.OpenSSLImplementation"><SSLHostConfig certificateVerificationAsString="REQUIRED" sslProtocol="TLS1.2" truststoreFile="c:/ApacheTomcat/servers/certs/abc.jks" truststorePassword="xyz"><Certificate certificateKeystoreFile="c:/ApacheTomcat/servers/certs/abc.jks" certificateKeystorePassword="xyz" type="UNDEFINED"/></SSLHostConfig></Connector>`

However, when I deploy a web app, I have to use a http connector to connect to tomcat manager app. So, there is another connector for this purpose that cause a security vulnerability. 

`<Connector port="8047" protocol="HTTP/1.1" connectionTimeout="20000"/>` 

So, what I want to do is to use the https connector for deploying apps, too.

Here is some exception logs for you when I try to connect at https://www.example.com:8447/manager

`Traceback (most recent call last):
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\virtualenvs\tomcatenv\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)`

**Comment by kotfu** [comment]
Understood. Renaming issue. I'll look at this and see what I can do.

**Comment by kotfu** [comment]
I think this will be fairly straight forward, here's the list of changes required:

- [ ] add keyword arguments to `connect()` for verify and certs, store values in attributes of TomcatManager
- [ ] modify `TomcatManager._get()` to use verify and certs attributes when calling `requests.get`
- [ ] update docstring for `connect()`
- [ ] add command line arguments to pytest for verify and certs
- [ ] add command line arguments to interactive `connect` command for verify and certs
- [ ] make interactive `which` command cert aware

**Comment by kotfu** [comment]
Work underway in `cert_auth` branch.

**Comment by kotfu** [comment]
@erentatar this is all done. Will be included in upcoming 3.0.0 release. I still have a bit of documentation clean up to do, but I think the release will happen this coming week.

**Comment by kotfu** [comment]
@erentatar. 3.0.0 has been released. Let me know if you have any issues with the new client certification authentication functionality. Documentation for this new capability is found at https://tomcatmanager.readthedocs.io/en/stable/authentication.html#ssl-tls-client-authentication
