### ISSUE TITLE
401 Client Error:  for url: http://localhost:8080/text/serverinfo

### ISSUE THREAD

**Issue by EysaN** [tomcatmanager/tomcatmanager#118]
I have been fighting with tomcat manager for the past month
Installed version of tomcat-manager
`3.0.0 (works with Tomcat >= 7.0 and <= 10.0)`

Installed version of tomcat;
~~~
Server version: Apache Tomcat/9.0.52
Server built:   Jul 31 2021 04:12:17 UTC
Server number:  9.0.52.0
OS Name:        Linux
OS Version:     4.14.243-185.433.amzn2.aarch64
Architecture:   aarch64
JVM Version:    1.8.0_302-b08
JVM Vendor:     Red Hat, Inc.
~~~

result of `cat /etc/os-release`
~~~
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
~~~
Whenever I run any example mentioned in this page (https://tomcatmanager.readthedocs.io/en/stable/package.html), I get "connected" and a regular output, so I am sure it is working this way and the credentials are correct.
here is a sample output:
~~~
connected
/ ApplicationState.RUNNING
/host-manager ApplicationState.RUNNING
/sales ApplicationState.RUNNING
/manager ApplicationState.RUNNING
~~~
However, when I try to run it from command line, it returns the error `requests.exceptions.HTTPError: 401 Client Error:  for url: http://localhost:8080/manager/text/serverinfo` at the first attempt.
The following line proves that tomcat is running at the time of the execution
~~~
sudo netstat -lnp | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      2438/java
~~~

**Comment by kotfu** [comment]
Sorry you are having issues. Can you share the exact command line invocation you are using? To execute the `serverinfo` command from the command line, you should do something like:
```
$ tomcat-manager http://localhost:8080/manager serverinfo
```

**Comment by EysaN** [comment]
hey @kotfu thanks for replying so quickly
strangely enough, I am running this command: `tomcat-manager --user=USER --password=PASSWORD http://localhost:8080/manager list` and get the error mentioned before

However, it works when I run `tomcat-manager` then `connect http://localhost:8080/manager USER PASSWORD` or I use server shortcuts which should be configured already, but this doesn't allow the flexibility of running the command against different tomcat instances from different places.

**Comment by kotfu** [comment]
I have been able to reproduce this error (linux client, linux server, tomcat 9.0.8). I'll investigate and get it resolved.

**Comment by EysaN** [comment]
Dear @kotfu, appreciate the help.

However, note that I kept having the issue after applying the fix locally, and there found another issue in the password of the user configured in tomcat-users.xml file.

The password has the character '$' like ABCD$EFGH, and whenever it used in the command `tomcat-manager --user=USER --password=ABCD$EFGH http://localhost:8080/manager`, tomcat-manager only considers `ABCD` as the password which is clearly incorrect and leads to `401 Client Error`

You can reproduce the issue by using any password string (including the  character '$'), then enable --debug flag and the used password will be printed.
For now, I have removed the character '$' and everything is working.

**Comment by kotfu** [comment]
I'll have a new release pushed to PYPI today (or maybe tomorrow) which should make it easier for you.

The reason the `$` is causing problems is because the operating system shell uses that as an indicator for a variable. The shell is looking for a variable called EFGH, which doesn't exist, so it uses an empty string instead.

You can tell the shell to not do so by enclosing the password in single quotes, like this:
```
$ tomcat-manager --user=USER --password='ABCD$EFGH' http://localhost:8080/manager
```
