### ISSUE TITLE
Not seeing sessions listed

### ISSUE THREAD

**Issue by opsup** [tomcatmanager/tomcatmanager#125]
I'm using v5.0.0 as installed via pip.

`
tomcat-manager> sessions /AlarmCenter
Default maximum session inactive interval is [600] minutes
Inactive for [<10] minutes: [2] sessions
tomcat-manager> tomcat-manager> serverinfo
Tomcat Version: [Apache Tomcat/9.0.39]
OS Name: [Linux]
OS Version: [4.18.0-348.2.1.el8_5.x86_64]
OS Architecture: [amd64]
JVM Version: [1.8.0_41-b04]
JVM Vendor: [Oracle Corporation]
tomcat-manager> 
`

Application was not deployed with a version.  I checked the online docs, but did not see much about the sessions cmd.  I'm expecting to see a list of session ids.  Maybe it only lists count?

**Comment by opsup** [comment]
Per the Tomcat documentation, /manager/text/sessions?path=/....  Does not list each session as the Manager HTML interface does.  I'll leave this open for confirmation and close.

**Comment by kotfu** [comment]
Correct. The [sessions command](https://tomcat.apache.org/tomcat-10.0-doc/manager-howto.html#Session_Statistics) in the Tomcat Manager web app counts the number of sessions in buckets based on how long they have been inactive. It does not list individual sessions. The python library in this project functions the same way. Closing the issue.
