### ISSUE TITLE
http error: 403 Forbidden

### ISSUE THREAD

**Issue by cross-hello** [tomcatmanager/tomcatmanager#137]
`tomcat-manager --user  user_name --password password_ http://192.168.1.73:8080/manager`
>> http error: 403 Forbidden

But if you open in browser, the html could be loaded.

**Comment by cross-hello** [comment]
the certificated html could be return, if you use `html=requests.get('http://192.168.1.73:8080/manager',auth=('user_name','password_'))`
![image](https://user-images.githubusercontent.com/42733664/212012358-b290bc52-e66c-4632-b13f-43ba6109e86a.png)

**Comment by kotfu** [comment]
Looks like you are using Tomcat 7.0.76, is that correct? If so, which version of tomcatmanager are you using?

**Comment by cross-hello** [comment]
Yes, **Tomcat**'s version is 7.0.76. And used **tomcatmanager**' is 4.0.0

**Comment by cross-hello** [comment]
Oh, we know it. Only suit for `Tomcat >= 8.0 and <= 10.0`
תודה אתה

**Comment by cross-hello** [comment]
Sir, after upgrade tomcat to 8.5.84, the problem still exists.
![image](https://user-images.githubusercontent.com/42733664/212221021-a3958796-d59d-4d93-9031-4f1988bff764.png)
![image](https://user-images.githubusercontent.com/42733664/212221110-dd46a9bc-f0f4-4ee9-a304-255555f39286.png)

**Comment by kotfu** [comment]
Can you post your `tomcat-users.xml` file without revealing any secrets? My current hypothesis is that the user `user_name` has not been granted the `manager-script` role. If you are not able to post your `tomcat-users.xml` file, perhaps you could review the configuration instructions at https://tomcatmanager.readthedocs.io/en/4.0.0/configuretomcat.html and confirm your setup matches the requirements outlined there.

**Comment by cross-hello** [comment]
Sorry, we forget to add ` manager-script` to user. 

Now the problem solved~

🌹
