### ISSUE TITLE
SyntaxError in interactive_tomcat_manager.py

### ISSUE THREAD

**Issue by heenak** [tomcatmanager/tomcatmanager#25]
Hi,

I am getting the below error as soon as I import tomcatmanager in python. 

  File "build\bdist.win32\egg\tomcatmanager\__init__.py", line 30, in <module>
  File "C:\Python27\lib\site-packages\tomcatmanager-0.9.1-py2.7.egg\tomcatmanage
r\interactive_tomcat_manager.py", line 194
    print(line.rstrip(), file=self.stdout)
                             ^
SyntaxError: invalid syntax 

Can you please help me how to resolve the same.

**Comment by kotfu** [comment]
It appears you are using Python 2.7, is that correct? This package requires Python 3.4 or higher.

I think the reason you are getting the error is because the syntax for `print` changed from python 2 to python 3.

Do you have the ability to install python 3.4?
