### ISSUE TITLE
Python 3.4 error

### ISSUE THREAD

**Issue by fenyoapa** [tomcatmanager/tomcatmanager#3]
I'm trying tomcat-manager.py with Python 3.4 and I get this error:
AttributeError: 'ExtendedRequest' object has no attribute 'has_data'

my command:
connect http://localhost:8186/manager/text [user] [pass]

I'm using tomcat-7.0.29.

can you help ?

thank you!

**Comment by kvonspiczak** [comment]
is there a solution for this? as soon as i try running the command without any params i'm getting this: 
`❯ tomcat-manager
Traceback (most recent call last):
  File "/usr/local/bin/tomcat-manager", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tomcatmanager/__main__.py", line 86, in main
    itm = tm.InteractiveTomcatManager()
  File "/usr/local/lib/python3.7/site-packages/tomcatmanager/interactive_tomcat_manager.py", line 185, in __init__
    self.settable.pop(setting)
AttributeError: 'InteractiveTomcatManager' object has no attribute 'settable'
`

**Comment by kotfu** [comment]
It looks like something in one of the upstream modules has changed, likely `cmd2`. I'm going to put this in a new issue since I think it's unrelated to this issue. I'll tag you on the new issue so you can follow it.

**Comment by kvonspiczak** [comment]
Great thank you! Yes my bad I was kind of in a rush while commenting and confused both error messages.
