### ISSUE TITLE
Deploy - add option on deploy to give context configuration file

### ISSUE THREAD

**Issue by easyrasta** [tomcatmanager/tomcatmanager#60]
It would be nice to add an option on deploy to give path of context configuraiton file
```
http://localhost:8080/manager/text/deploy?config=file:/path/context.xml
```

**Comment by kotfu** [comment]
I have a [pending pull request](https://github.com/python-cmd2/cmd2/pull/247) on upstream cmd2 to add argparse support, which I think will likely be accepted. Once that happens, I'll use that cmd2 argparse code to rework the deploy command so it can better accommodate the context.xml.

**Comment by kotfu** [comment]
Just pushed updates to `develop` branch with full support for deploying via context configuration files. Includes documentation and inline help and updated CHANGELOG. I've got a couple more things to do to catch up with some changes made in cmd2 version 0.8.0, and then I'll make a new release and push it to pypi.
