### ISSUE TITLE
Not able to connect to tomcat manager

### ISSUE THREAD

**Issue by abhicool92** [tomcatmanager/tomcatmanager#73]
![image](https://user-images.githubusercontent.com/33102268/42185603-17fee668-7e0f-11e8-9385-92ab27d79e90.png)

![image](https://user-images.githubusercontent.com/33102268/42185648-46e8ffc2-7e0f-11e8-98f2-a3d5fae44b3a.png)
![image](https://user-images.githubusercontent.com/33102268/42185931-4d7fdee0-7e10-11e8-923a-33fd5eb58f57.png)

![image](https://user-images.githubusercontent.com/33102268/42185554-efff2df8-7e0e-11e8-88d3-de1c6d5ea3ee.png)

![image](https://user-images.githubusercontent.com/33102268/42185672-65fde10c-7e0f-11e8-8f0e-7ae490eb4e4d.png)

Not able to establish a connection to the application manager through tomcat-manager.

**Comment by kotfu** [comment]
Sorry you have been disrupted by this issue. The upstream `cmd2` package is under heavy development, and they have made a change which causes the issue you have reported. I have it fixed on the `devel` branch of this project, but have not made a new PyPi release yet. I was hoping to wait for another upstream dependency (PyYAML) to make a new release that supports Python 3.7.

In an update https://github.com/yaml/pyyaml/issues/193 posted 30 minutes ago, they PyYAML team estimates 24-48 hours for a python 3.7 compatible release. My plan is to make a new tomcat manager release as soon as PyYAML is out.

**Comment by abhicool92** [comment]
@kotfu Thanks for your response. Will be looking forward for the new release of tomcat manager.

**Comment by kotfu** [comment]
PyYaml is all fixed, and 0.13.0 has been uploaded to Pypi.
