### ISSUE TITLE
settable error

### ISSUE THREAD

**Issue by kotfu** [tomcatmanager/tomcatmanager#77]
Originally reported by @kvonspiczak on issue #3. Since it's unrelated, moving it to a new issue.

is there a solution for this? as soon as i try running the command without any params i'm getting this:
❯ tomcat-manager Traceback (most recent call last): File "/usr/local/bin/tomcat-manager", line 10, in <module> sys.exit(main()) File "/usr/local/lib/python3.7/site-packages/tomcatmanager/__main__.py", line 86, in main itm = tm.InteractiveTomcatManager() File "/usr/local/lib/python3.7/site-packages/tomcatmanager/interactive_tomcat_manager.py", line 185, in __init__ self.settable.pop(setting) AttributeError: 'InteractiveTomcatManager' object has no attribute 'settable'

**Comment by kotfu** [comment]
I think it's related to a change in upstream `cmd2` module. I'll investigate.

**Comment by dizzle667** [comment]
I'm having the exact same issue. Is there any fix or workaround yet?
I installed tomcatmanager 0.13.0 with pip

**Comment by kotfu** [comment]
I have identified the issue and have it fixed. I’ll push a new version to PyPi later today.

**Comment by kvonspiczak** [comment]
great, looking forward to give it a try!

**Comment by kotfu** [comment]
New release 0.14.0 pushed to pypi. Should resolve this issue. It was a problem with upstream `cmd2` module.

**Comment by dizzle667** [comment]
Perfect, the error is gone now. Thank you very much :)
