### ISSUE TITLE
Add command line option to control timeout

### ISSUE THREAD

**Issue by dizzle667** [tomcatmanager/tomcatmanager#79]
currently, the request timeout seems to be 10 seconds, which is not enough for me for a deployment. Is there any way to change the timeout value or would it be possible to implement a command line parameter "--timeout" for this?

The error I see is this:
HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=10)

The deployment of the WAR file works like a charm, but in my example the deployment takes about 60-80 seconds before the HTTP response 200 is returned.

**Comment by kotfu** [comment]
There isn't currently a timeout command line parameter, but I will certainly consider that as an enhancement request. However, you can change the timeout values within the command line shell. See https://tomcatmanager.readthedocs.io/en/stable/interactive.html#settings for the particulars. Settings you change in the interactive shell should persist, and be applicable when you run `tomcat-manager` with only command line parameters.

I'm going to rename this issue to add a command-line option for the timeout, and leave it open.

**Comment by Sam-Hall** [comment]
I'm on version 1.0.1 and using --timeout=nn on the commandline doesn't seem to do anything. It still times out after 10 seconds. I tried creating an ini file manually and it just crashed. I'll try again using the command prompt.
