### ISSUE TITLE
cmd2>=0.10 does not uses settable

### ISSUE THREAD

**Issue by bitozoid** [tomcatmanager/tomcatmanager#82]
I had this error:

```
>>> from tomcatmanager import InteractiveTomcatManager as itm 
>>> itm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/tomcatmanager/interactive_tomcat_manager.py", line 192, in __init__
    self.settable.pop(setting)
AttributeError: 'InteractiveTomcatManager' object has no attribute 'settable'
```

It looks that newer versions of _cmd2_ (`cmd2>=0.10`) do not uses `settable` anymore. See [cmd2 changelog](https://github.com/python-cmd2/cmd2/blob/master/CHANGELOG.md).

I would pin _cmd2_ version to something like `<0.10` until it is fixed.

**Comment by kotfu** [comment]
Yup, `cmd2` has rolled out a lot of breaking changes recently. This will be easy to fix, I'll publish a new release of tomcatmanager shortly.

**Comment by kotfu** [comment]
New release of tomcatmanager 1.0.1 published to pypi. Should resolve this issue.
